FROM openjdk:11-jdk-slim
RUN apk --no-cache add curl
VOLUME /tmp
ARG REGION_ARG=us-east-1
ARG ACCESS_ARG=secrets.AWS_ACCESS_KEY_ID
ARG SECRET_ARG=secrets.AWS_SECRET_ACCESS_KEY
ENV AWS_REGION=$REGION_ARG
ENV AWS_ACCESS_KEY=$ACCESS_ARG
ENV AWS_SECRET_KEY=$SECRET_ARG
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
